-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:28:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EJEMPLOS.2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EJEMPLOS.2` ;

-- -----------------------------------------------------
-- Schema EJEMPLOS.2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EJEMPLOS.2` DEFAULT CHARACTER SET utf8 ;
USE `EJEMPLOS.2` ;

-- -----------------------------------------------------
-- Table `EJEMPLOS.2`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJEMPLOS.2`.`EMPLEADO` (
  `Nif` INT NULL,
  `Nombre` VARCHAR(10) NOT NULL,
  `Nombre2` VARCHAR(10) NOT NULL,
  `Apelido` VARCHAR(10) NOT NULL,
  `Apellido2` VARCHAR(10) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJEMPLOS.2`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJEMPLOS.2`.`DEPARTAMENTO` (
  `Cod-Dpto` INT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod-Dpto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJEMPLOS.2`.`E-D`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJEMPLOS.2`.`E-D` (
  `EMPLEADO_Nif` INT NOT NULL,
  `DEPARTAMENTO_Cod-Dpto` INT NOT NULL,
  PRIMARY KEY (`EMPLEADO_Nif`, `DEPARTAMENTO_Cod-Dpto`),
  CONSTRAINT `fk_EMP-DPTO_EMPLEADO`
    FOREIGN KEY (`EMPLEADO_Nif`)
    REFERENCES `EJEMPLOS.2`.`EMPLEADO` (`Nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMP-DPTO_DEPARTAMENTO1`
    FOREIGN KEY (`DEPARTAMENTO_Cod-Dpto`)
    REFERENCES `EJEMPLOS.2`.`DEPARTAMENTO` (`Cod-Dpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EMP-DPTO_DEPARTAMENTO1_idx` ON `EJEMPLOS.2`.`E-D` (`DEPARTAMENTO_Cod-Dpto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
