-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:41:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 5.6Transformacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `5.6Transformacion` ;

-- -----------------------------------------------------
-- Schema 5.6Transformacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `5.6Transformacion` DEFAULT CHARACTER SET utf8 ;
USE `5.6Transformacion` ;

-- -----------------------------------------------------
-- Table `5.6Transformacion`.`PILOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5.6Transformacion`.`PILOTO` (
  `nif` INT NOT NULL,
  `Nombre` VARCHAR(10) NOT NULL,
  `Nombre2` VARCHAR(10) NOT NULL,
  `Apellido1` VARCHAR(10) NOT NULL,
  `Apellido2` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `5.6Transformacion`.`CIUDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5.6Transformacion`.`CIUDAD` (
  `nombre-ciudad` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(15) NOT NULL,
  `numero-habitantes` INT NOT NULL,
  PRIMARY KEY (`nombre-ciudad`, `pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `5.6Transformacion`.`AVION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5.6Transformacion`.`AVION` (
  `cod-avion` VARCHAR(20) NOT NULL,
  `nombre-avion` VARCHAR(45) NOT NULL,
  `numero-motores` INT NOT NULL,
  PRIMARY KEY (`cod-avion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `5.6Transformacion`.`P-C-A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5.6Transformacion`.`P-C-A` (
  `fecha` DATE NOT NULL,
  `PILOTO_nif` INT NOT NULL,
  `CIUDAD_nombre-ciudad` VARCHAR(50) NOT NULL,
  `CIUDAD_pais` VARCHAR(15) NOT NULL,
  `AVION_cod-avion` VARCHAR(20) NOT NULL,
  CONSTRAINT `fk_P-C-A_PILOTO`
    FOREIGN KEY (`PILOTO_nif`)
    REFERENCES `5.6Transformacion`.`PILOTO` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P-C-A_CIUDAD1`
    FOREIGN KEY (`CIUDAD_nombre-ciudad` , `CIUDAD_pais`)
    REFERENCES `5.6Transformacion`.`CIUDAD` (`nombre-ciudad` , `pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P-C-A_AVION1`
    FOREIGN KEY (`AVION_cod-avion`)
    REFERENCES `5.6Transformacion`.`AVION` (`cod-avion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_P-C-A_PILOTO_idx` ON `5.6Transformacion`.`P-C-A` (`PILOTO_nif` ASC) VISIBLE;

CREATE INDEX `fk_P-C-A_CIUDAD1_idx` ON `5.6Transformacion`.`P-C-A` (`CIUDAD_nombre-ciudad` ASC, `CIUDAD_pais` ASC) VISIBLE;

CREATE INDEX `fk_P-C-A_AVION1_idx` ON `5.6Transformacion`.`P-C-A` (`AVION_cod-avion` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
