-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:40:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 5.3-2COCHE_PILOTO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `5.3-2COCHE_PILOTO` ;

-- -----------------------------------------------------
-- Schema 5.3-2COCHE_PILOTO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `5.3-2COCHE_PILOTO` DEFAULT CHARACTER SET utf8 ;
USE `5.3-2COCHE_PILOTO` ;

-- -----------------------------------------------------
-- Table `5.3-2COCHE_PILOTO`.`PILOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5.3-2COCHE_PILOTO`.`PILOTO` (
  `Nif` INT NOT NULL,
  `Nombre` VARCHAR(10) NULL,
  `Nombre2` VARCHAR(45) NULL,
  `Apellido1` VARCHAR(45) NULL,
  `Apellido2` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `COCHE_Matricula` INT NOT NULL,
  PRIMARY KEY (`Nif`, `COCHE_Matricula`),
  CONSTRAINT `fk_PILOTO_COCHE1`
    FOREIGN KEY (`COCHE_Matricula`)
    REFERENCES `5.3-2COCHE_PILOTO`.`COCHE` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PILOTO_COCHE1_idx` ON `5.3-2COCHE_PILOTO`.`PILOTO` (`COCHE_Matricula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `5.3-2COCHE_PILOTO`.`COCHE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5.3-2COCHE_PILOTO`.`COCHE` (
  `Matricula` INT NOT NULL,
  `Asientos` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `PILOTO_Nif` INT NOT NULL,
  PRIMARY KEY (`Matricula`, `PILOTO_Nif`),
  CONSTRAINT `fk_COCHE_PILOTO`
    FOREIGN KEY (`PILOTO_Nif`)
    REFERENCES `5.3-2COCHE_PILOTO`.`PILOTO` (`Nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_COCHE_PILOTO_idx` ON `5.3-2COCHE_PILOTO`.`COCHE` (`PILOTO_Nif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `5.3-2COCHE_PILOTO`.`P-C`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5.3-2COCHE_PILOTO`.`P-C` (
  `PILOTO_Nif` INT NOT NULL,
  `PILOTO_COCHE_Matricula` INT NOT NULL,
  PRIMARY KEY (`PILOTO_Nif`, `PILOTO_COCHE_Matricula`),
  CONSTRAINT `fk_P-C_PILOTO1`
    FOREIGN KEY (`PILOTO_Nif` , `PILOTO_COCHE_Matricula`)
    REFERENCES `5.3-2COCHE_PILOTO`.`PILOTO` (`Nif` , `COCHE_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
